;; racket/unsafe/ops
#lang racket/base
(provide plain-map re-exports)

;; re-exports (0)
(define re-exports '())

;; plain (0/196 translated)
(define plain-map (hash
  'unsafe-assert-unreachable  #f
  'unsafe-box*-cas!  #f
  'unsafe-bytes->immutable-bytes!  #f
  'unsafe-bytes-copy!  #f
  'unsafe-bytes-length  #f
  'unsafe-bytes-ref  #f
  'unsafe-bytes-set!  #f
  'unsafe-car  #f
  'unsafe-cdr  #f
  'unsafe-chaperone-procedure  #f
  'unsafe-chaperone-vector  #f
  'unsafe-char->integer  #f
  'unsafe-char<=?  #f
  'unsafe-char<?  #f
  'unsafe-char=?  #f
  'unsafe-char>=?  #f
  'unsafe-char>?  #f
  'unsafe-cons-list  #f
  'unsafe-ephemeron-hash-iterate-first  #f
  'unsafe-ephemeron-hash-iterate-key  #f
  'unsafe-ephemeron-hash-iterate-key+value  #f
  'unsafe-ephemeron-hash-iterate-next  #f
  'unsafe-ephemeron-hash-iterate-pair  #f
  'unsafe-ephemeron-hash-iterate-value  #f
  'unsafe-extfl*  #f
  'unsafe-extfl+  #f
  'unsafe-extfl-  #f
  'unsafe-extfl->fx  #f
  'unsafe-extfl/  #f
  'unsafe-extfl<  #f
  'unsafe-extfl<=  #f
  'unsafe-extfl=  #f
  'unsafe-extfl>  #f
  'unsafe-extfl>=  #f
  'unsafe-extflabs  #f
  'unsafe-extflacos  #f
  'unsafe-extflasin  #f
  'unsafe-extflatan  #f
  'unsafe-extflceiling  #f
  'unsafe-extflcos  #f
  'unsafe-extflexp  #f
  'unsafe-extflexpt  #f
  'unsafe-extflfloor  #f
  'unsafe-extfllog  #f
  'unsafe-extflmax  #f
  'unsafe-extflmin  #f
  'unsafe-extflround  #f
  'unsafe-extflsin  #f
  'unsafe-extflsqrt  #f
  'unsafe-extfltan  #f
  'unsafe-extfltruncate  #f
  'unsafe-extflvector-length  #f
  'unsafe-extflvector-ref  #f
  'unsafe-extflvector-set!  #f
  'unsafe-f64vector-ref  #f
  'unsafe-f64vector-set!  #f
  'unsafe-f80vector-ref  #f
  'unsafe-f80vector-set!  #f
  'unsafe-fl*  #f
  'unsafe-fl+  #f
  'unsafe-fl-  #f
  'unsafe-fl->fx  #f
  'unsafe-fl/  #f
  'unsafe-fl<  #f
  'unsafe-fl<=  #f
  'unsafe-fl=  #f
  'unsafe-fl>  #f
  'unsafe-fl>=  #f
  'unsafe-flabs  #f
  'unsafe-flacos  #f
  'unsafe-flasin  #f
  'unsafe-flatan  #f
  'unsafe-flbit-field  #f
  'unsafe-flceiling  #f
  'unsafe-flcos  #f
  'unsafe-flexp  #f
  'unsafe-flexpt  #f
  'unsafe-flfloor  #f
  'unsafe-flimag-part  #f
  'unsafe-fllog  #f
  'unsafe-flmax  #f
  'unsafe-flmin  #f
  'unsafe-flrandom  #f
  'unsafe-flreal-part  #f
  'unsafe-flround  #f
  'unsafe-flsin  #f
  'unsafe-flsingle  #f
  'unsafe-flsqrt  #f
  'unsafe-fltan  #f
  'unsafe-fltruncate  #f
  'unsafe-flvector-length  #f
  'unsafe-flvector-ref  #f
  'unsafe-flvector-set!  #f
  'unsafe-fx*  #f
  'unsafe-fx*/wraparound  #f
  'unsafe-fx+  #f
  'unsafe-fx+/wraparound  #f
  'unsafe-fx-  #f
  'unsafe-fx-/wraparound  #f
  'unsafe-fx->extfl  #f
  'unsafe-fx->fl  #f
  'unsafe-fx<  #f
  'unsafe-fx<=  #f
  'unsafe-fx=  #f
  'unsafe-fx>  #f
  'unsafe-fx>=  #f
  'unsafe-fxabs  #f
  'unsafe-fxand  #f
  'unsafe-fxior  #f
  'unsafe-fxlshift  #f
  'unsafe-fxlshift/wraparound  #f
  'unsafe-fxmax  #f
  'unsafe-fxmin  #f
  'unsafe-fxmodulo  #f
  'unsafe-fxnot  #f
  'unsafe-fxpopcount  #f
  'unsafe-fxpopcount16  #f
  'unsafe-fxpopcount32  #f
  'unsafe-fxquotient  #f
  'unsafe-fxremainder  #f
  'unsafe-fxrshift  #f
  'unsafe-fxrshift/logical  #f
  'unsafe-fxvector-length  #f
  'unsafe-fxvector-ref  #f
  'unsafe-fxvector-set!  #f
  'unsafe-fxxor  #f
  'unsafe-immutable-hash-iterate-first  #f
  'unsafe-immutable-hash-iterate-key  #f
  'unsafe-immutable-hash-iterate-key+value  #f
  'unsafe-immutable-hash-iterate-next  #f
  'unsafe-immutable-hash-iterate-pair  #f
  'unsafe-immutable-hash-iterate-value  #f
  'unsafe-impersonate-procedure  #f
  'unsafe-impersonate-vector  #f
  'unsafe-list-ref  #f
  'unsafe-list-tail  #f
  'unsafe-make-flrectangular  #f
  'unsafe-make-signal-received  #f
  'unsafe-make-srcloc  #f
  'unsafe-mcar  #f
  'unsafe-mcdr  #f
  'unsafe-mutable-hash-iterate-first  #f
  'unsafe-mutable-hash-iterate-key  #f
  'unsafe-mutable-hash-iterate-key+value  #f
  'unsafe-mutable-hash-iterate-next  #f
  'unsafe-mutable-hash-iterate-pair  #f
  'unsafe-mutable-hash-iterate-value  #f
  'unsafe-poll-fd  #f
  'unsafe-s16vector-ref  #f
  'unsafe-s16vector-set!  #f
  'unsafe-set-box!  #f
  'unsafe-set-box*!  #f
  'unsafe-set-immutable-car!  #f
  'unsafe-set-immutable-cdr!  #f
  'unsafe-set-mcar!  #f
  'unsafe-set-mcdr!  #f
  'unsafe-stencil-vector  #f
  'unsafe-stencil-vector-length  #f
  'unsafe-stencil-vector-mask  #f
  'unsafe-stencil-vector-ref  #f
  'unsafe-stencil-vector-set!  #f
  'unsafe-stencil-vector-update  #f
  'unsafe-string->immutable-string!  #f
  'unsafe-string-length  #f
  'unsafe-string-ref  #f
  'unsafe-string-set!  #f
  'unsafe-struct*-cas!  #f
  'unsafe-struct*-ref  #f
  'unsafe-struct*-set!  #f
  'unsafe-struct*-type  #f
  'unsafe-struct-ref  #f
  'unsafe-struct-set!  #f
  'unsafe-u16vector-ref  #f
  'unsafe-u16vector-set!  #f
  'unsafe-unbox  #f
  'unsafe-unbox*  #f
  'unsafe-vector*->immutable-vector!  #f
  'unsafe-vector*-append  #f
  'unsafe-vector*-cas!  #f
  'unsafe-vector*-copy  #f
  'unsafe-vector*-length  #f
  'unsafe-vector*-ref  #f
  'unsafe-vector*-set!  #f
  'unsafe-vector*-set/copy  #f
  'unsafe-vector-append  #f
  'unsafe-vector-copy  #f
  'unsafe-vector-length  #f
  'unsafe-vector-ref  #f
  'unsafe-vector-set!  #f
  'unsafe-vector-set/copy  #f
  'unsafe-weak-hash-iterate-first  #f
  'unsafe-weak-hash-iterate-key  #f
  'unsafe-weak-hash-iterate-key+value  #f
  'unsafe-weak-hash-iterate-next  #f
  'unsafe-weak-hash-iterate-pair  #f
  'unsafe-weak-hash-iterate-value  #f
))

