;; mrlib/image-core
#lang racket/base
(provide plain-map re-exports)

;; re-exports (2)
(define re-exports '(
  "racket/math"
  "snip-lib/racket/snip"
))

;; plain (157)
(define plain-map (hash
  'angle->proper-range  #f
  'atomic-shape?  #f
  'bb  #f
  'bb-baseline  #f
  'bb-bottom  #f
  'bb-right  #f
  'bb?  #f
  'bitmap->image  #f
  'build-pulled-point  #f
  'c->xy  #f
  'cn-or-simple-shape?  #f
  'color  #f
  'color-alpha  #f
  'color-blue  #f
  'color-green  #f
  'color-red  #f
  'color?  #f
  'compute-image-cache  #f
  'crop-points  #f
  'crop-shape  #f
  'crop?  #f
  'curve-segment->path  #f
  'curve-segment-color  #f
  'curve-segment-e-angle  #f
  'curve-segment-e-pull  #f
  'curve-segment-end  #f
  'curve-segment-mode  #f
  'curve-segment-s-angle  #f
  'curve-segment-s-pull  #f
  'curve-segment-start  #f
  'curve-segment?  #f
  'definitely-same-image?  #f
  'degrees->complex  #f
  'ellipse-angle  #f
  'ellipse-color  #f
  'ellipse-height  #f
  'ellipse-mode  #f
  'ellipse-outermost-point-x  #f
  'ellipse-outermost-point-y  #f
  'ellipse-rotated-size  #f
  'ellipse-t->x  #f
  'ellipse-t->y  #f
  'ellipse-wedge  #f
  'ellipse-width  #f
  'ellipse?  #f
  'extra-2htdp/image-colors  #f
  'flip-flipped?  #f
  'flip-shape  #f
  'flip?  #f
  'get-bb  #f
  'get-normalized-shape  #f
  'get-normalized?  #f
  'get-pinhole  #f
  'get-shape  #f
  'ibitmap-angle  #f
  'ibitmap-cache  #f
  'ibitmap-raw-bitmap  #f
  'ibitmap-x-scale  #f
  'ibitmap-y-scale  #f
  'ibitmap?  #f
  'image%  #f
  'image->snipclass-bytes  #f
  'image-bb  #f
  'image-normalized?  #f
  'image-shape  #f
  'image-snip->image  #f
  'image?  #f
  'line-segment-color  #f
  'line-segment-end  #f
  'line-segment-start  #f
  'line-segment?  #f
  'make-bb  #f
  'make-color  #f
  'make-crop  #f
  'make-curve-segment  #f
  'make-ellipse  #f
  'make-flip  #f
  'make-ibitmap  #f
  'make-image  #f
  'make-line-segment  #f
  'make-overlay  #f
  'make-pen  #f
  'make-point  #f
  'make-polygon  #f
  'make-pulled-point  #f
  'make-scale  #f
  'make-text  #f
  'make-translate  #f
  'mode-color->pen  #f
  'normalize-shape  #f
  'normalized-shape?  #f
  'np-atomic-shape?  #f
  'overlay-bottom  #f
  'overlay-top  #f
  'overlay?  #f
  'pen  #f
  'pen-cap  #f
  'pen-color  #f
  'pen-join  #f
  'pen-style  #f
  'pen-width  #f
  'pen?  #f
  'point  #f
  'point-x  #f
  'point-y  #f
  'point?  #f
  'points->ltrb-values  #f
  'polygon-color  #f
  'polygon-mode  #f
  'polygon-points  #f
  'polygon?  #f
  'pulled-point  #f
  'pulled-point-langle  #f
  'pulled-point-lpull  #f
  'pulled-point-rangle  #f
  'pulled-point-rpull  #f
  'pulled-point-x  #f
  'pulled-point-y  #f
  'pulled-point?  #f
  'render-image  #f
  'render-normalized  #f
  'rotate-c  #f
  'rotate-points  #f
  'save-image-as-bitmap  #f
  'scale-np-atomic  #f
  'scale-shape  #f
  'scale-x  #f
  'scale-y  #f
  'scale?  #f
  'simple-shape?  #f
  'skip-image-equality-fast-path  #f
  'snip-class  #f
  'snipclass-bytes->image  #f
  'string->color-object/f  #f
  'struct:bb  #f
  'struct:color  #f
  'struct:point  #f
  'struct:pulled-point  #f
  'text->font  #f
  'text-angle  #f
  'text-color  #f
  'text-face  #f
  'text-family  #f
  'text-size  #f
  'text-string  #f
  'text-style  #f
  'text-underline  #f
  'text-weight  #f
  'text-y-scale  #f
  'text?  #f
  'to-img  #f
  'translate-dx  #f
  'translate-dy  #f
  'translate-shape  #f
  'translate?  #f
  'un/cache-image  #f
  'xy->c  #f
))

