;; racket/contract
#lang racket/base
(provide plain-map kw-map re-exports)

;; re-exports (0)
(define re-exports '())

;; plain (200/202 translated)
(define plain-map (hash
  '*list/c  "*列表/契约"
  '->  #f
  '->*  #f
  '->d  "->依赖"
  '->i  "->不可变"
  '</c  "</契约"
  '<=/c  "<=/契约"
  '=/c  "=/契约"
  '>/c  ">/契约"
  '>=/c  ">=/契约"
  'and/c  "与/契约"
  'any  "任意"
  'any/c  "任意/契约"
  'arity-checking-wrapper  "元数-检查-包装器"
  'arrow-contract-info  "箭头-契约-信息"
  'arrow-contract-info-accepts-arglist  "箭头-契约-信息-接受-参数列表"
  'arrow-contract-info-chaperone-procedure  "箭头-契约-信息-监护-过程"
  'arrow-contract-info-check-first-order  "箭头-契约-信息-检查-一阶"
  'arrow-contract-info?  "箭头-契约-信息?"
  'base->-doms/c  "基础->-域/契约"
  'base->-rngs/c  "基础->-范围/契约"
  'base->?  "基础->?"
  'between/c  "之间/契约"
  'blame-add-car-context  "责备-添加-取首-上下文"
  'blame-add-cdr-context  "责备-添加-取余-上下文"
  'blame-add-missing-party  "责备-添加-缺失-方"
  'blame-add-nth-arg-context  "责备-添加-第n-参数-上下文"
  'blame-add-range-context  "责备-添加-范围-上下文"
  'blame-add-unknown-context  "责备-添加-未知-上下文"
  'blame-context  "责备-上下文"
  'blame-contract  "责备-契约"
  'blame-fmt->-string  "责备-格式->字符串"
  'blame-missing-party?  "责备-缺失-方?"
  'blame-negative  "责备-负面"
  'blame-original?  "责备-原始?"
  'blame-positive  "责备-正面"
  'blame-replace-negative  "责备-替换-负面"
  'blame-replaced-negative?  "责备-已替换-负面?"
  'blame-source  "责备-源"
  'blame-swap  "责备-交换"
  'blame-swapped?  "责备-已交换?"
  'blame-update  "责备-更新"
  'blame-value  "责备-值"
  'blame?  "责备?"
  'box-immutable/c  "盒-不可变/契约"
  'build-compound-type-name  "构建-复合-类型-名称"
  'case->  "分支->"
  'channel/c  "通道/契约"
  'chaperone-contract-property?  "监护-契约-属性?"
  'chaperone-contract?  "监护-契约?"
  'char-in  "字符-在"
  'char-in/c  "字符-在/契约"
  'coerce-chaperone-contract  "强制-监护-契约"
  'coerce-chaperone-contracts  "强制-监护-契约集"
  'coerce-contract  "强制-契约"
  'coerce-contract/f  "强制-契约/f"
  'coerce-contracts  "强制-契约集"
  'coerce-flat-contract  "强制-平坦-契约"
  'coerce-flat-contracts  "强制-平坦-契约集"
  'complex/c  "复数/契约"
  'cons/c  "构造/契约"
  'cons/dc  "构造/依赖契约"
  'continuation-mark-key/c  "续延-标记-键/契约"
  'contract  "契约"
  'contract-continuation-mark-key  "契约-续延-标记-键"
  'contract-custom-write-property-proc  "契约-自定义-写入-属性-过程"
  'contract-equivalent?  "契约-等价?"
  'contract-first-order  "契约-一阶"
  'contract-first-order-passes?  "契约-一阶-通过?"
  'contract-in  "契约-入"
  'contract-late-neg-projection  "契约-后期-否定-投影"
  'contract-name  "契约-名称"
  'contract-out  "契约-出"
  'contract-pos/neg-doubling  "契约-正面/负面-加倍"
  'contract-proc  "契约-过程"
  'contract-projection  "契约-投影"
  'contract-property?  "契约-属性?"
  'contract-random-generate  "契约-随机-生成"
  'contract-random-generate-env?  "契约-随机-生成-环境?"
  'contract-random-generate-fail  "契约-随机-生成-失败"
  'contract-random-generate-fail?  "契约-随机-生成-失败?"
  'contract-random-generate-get-current-environment  "契约-随机-生成-获取-当前-环境"
  'contract-random-generate-stash  "契约-随机-生成-暂存"
  'contract-random-generate/choose  "契约-随机-生成/选择"
  'contract-stronger?  "契约-更强?"
  'contract-struct  "契约-结构"
  'contract-struct-exercise  "契约-结构-练习"
  'contract-struct-generate  "契约-结构-生成"
  'contract-struct-late-neg-projection  "契约-结构-后期-否定-投影"
  'contract-struct-list-contract?  "契约-结构-列表-契约?"
  'contract-val-first-projection  "契约-值-优先-投影"
  'contract?  "契约?"
  'current-blame-format  "当前-责备-格式"
  'current-contract-region  "当前-契约-区域"
  'custom-write-property-proc  "自定义-写入-属性-过程"
  'define-contract-struct  "定义-契约-结构"
  'define-module-boundary-contract  "定义-模块-边界-契约"
  'define-opt/c  "定义-可选/契约"
  'define-struct/contract  "定义-结构/契约"
  'define/contract  "定义/契约"
  'define/final-prop  "定义/最终-属性"
  'define/subexpression-pos-prop  "定义/子表达式-位置-属性"
  'define/subexpression-pos-prop/name  "定义/子表达式-位置-属性/名称"
  'eq-contract-val  "eq-契约-值"
  'eq-contract?  "eq-契约?"
  'equal-contract-val  "相等-契约-值"
  'equal-contract?  "相等-契约?"
  'evt/c  "事件/契约"
  'exn:fail:contract:blame  "异常:失败:契约:责备"
  'exn:fail:contract:blame-object  "异常:失败:契约:责备-对象"
  'exn:fail:contract:blame?  "异常:失败:契约:责备?"
  'failure-result/c  "失败-结果/契约"
  'false/c  "假/契约"
  'first-or/c  "优先-或/契约"
  'flat-contract  "平坦-契约"
  'flat-contract-predicate  "平坦-契约-谓词"
  'flat-contract-property?  "平坦-契约-属性?"
  'flat-contract?  "平坦-契约?"
  'flat-murec-contract  "平坦-互递归-契约"
  'flat-named-contract  "平坦-命名-契约"
  'flat-rec-contract  "平坦-递归-契约"
  'get/build-late-neg-projection  "获取/构建-后期-否定-投影"
  'get/build-val-first-projection  "获取/构建-值-优先-投影"
  'has-blame?  "有-责备?"
  'has-contract?  "有-契约?"
  'hash/dc  "哈希/依赖契约"
  'if/c  "如果/契约"
  'impersonator-contract?  "冒充-契约?"
  'impersonator-prop:blame  "冒充-属性:责备"
  'impersonator-prop:contracted  "冒充-属性:已契约"
  'integer-in  "整数-在"
  'invariant-assertion  "不变-断言"
  'keywords-match  "关键字-匹配"
  'list*of  "列表*之"
  'list-contract?  "列表-契约?"
  'list/c  "列表/契约"
  'listof  "列表之"
  'make-exn:fail:contract:blame  "创建-异常:失败:契约:责备"
  'make-none/c  "创建-无/契约"
  'make-proj-contract  "创建-投影-契约"
  'matches-arity-exactly?  "匹配-元数-完全?"
  'mutable-treelist/c  "可变-树列表/契约"
  'n->th  "n->第"
  'natural-number/c  "自然-数/契约"
  'new-∀/c  "新-∀/契约"
  'new-∃/c  "新-∃/契约"
  'non-empty-listof  "非-空-列表之"
  'none/c  "无/契约"
  'not/c  "非/契约"
  'one-of/c  "之一/契约"
  'opt/c  "可选/契约"
  'or/c  "或/契约"
  'parametric->/c  "参数->/契约"
  'predicate/c  "谓词/契约"
  'printable/c  "可打印/契约"
  'procedure-arity-includes/c  "过程-元数-包含/契约"
  'promise/c  "承诺/契约"
  'prompt-tag/c  "提示-标签/契约"
  'prop:arrow-contract  "属性:箭头-契约"
  'prop:arrow-contract-get-info  "属性:箭头-契约-获取-信息"
  'prop:arrow-contract?  "属性:箭头-契约?"
  'prop:blame  "属性:责备"
  'prop:chaperone-contract  "属性:监护-契约"
  'prop:contract  "属性:契约"
  'prop:contracted  "属性:已契约"
  'prop:flat-contract  "属性:平坦-契约"
  'prop:orc-contract  "属性:ORC-契约"
  'prop:orc-contract-get-subcontracts  "属性:ORC-契约-获取-子契约"
  'prop:orc-contract?  "属性:ORC-契约?"
  'prop:recursive-contract  "属性:递归-契约"
  'prop:recursive-contract-unroll  "属性:递归-契约-展开"
  'prop:recursive-contract?  "属性:递归-契约?"
  'provide/contract  "提供/契约"
  'raise-contract-error  "引发-契约-错误"
  'real-in  "实数-在"
  'recontract-out  "重新契约-出"
  'recursive-contract  "递归-契约"
  'rename-contract  "重命名-契约"
  'skip-projection-wrapper?  "跳过-投影-包装器?"
  'string-len/c  "字符串-长度/契约"
  'struct-guard/c  "结构-守卫/契约"
  'struct-type-property/c  "结构-类型-属性/契约"
  'struct/c  "结构/契约"
  'struct/contract  "结构/合约"
  'struct/dc  "结构/依赖契约"
  'struct:arrow-contract-info  "结构:箭头-契约-信息"
  'struct:exn:fail:contract:blame  "结构:异常:失败:契约:责备"
  'suggest/c  "建议/契约"
  'symbols  "符号"
  'syntax/c  "语法/契约"
  'tail-marks-match?  "尾部-标记-匹配?"
  'the-unsupplied-arg  "未提供的-参数"
  'unconstrained-domain->  "无约束-域->"
  'unspecified-dom  "未指定-域"
  'unsupplied-arg?  "未提供-参数?"
  'value-blame  "值-责备"
  'value-contract  "值-契约"
  'values/drop  "值/丢弃"
  'vector-immutable/c  "向量-不可变/契约"
  'vector-immutableof  "向量-不可变之"
  'with-contract  "带-契约"
  'with-contract-continuation-mark  "带-契约-续延-标记"
))

;; with-kw (20)
(define kw-map (hash
  'bad-number-of-results  (cons "错误-结果-数" (hash '#:missing-party #f))
  'blame-add-context  (cons "责备-添加-上下文" (hash '#:important #f '#:swap? #f))
  'box/c  (cons "箱/契约" (hash '#:flat? #f '#:immutable #f))
  'build-chaperone-contract-property  (cons "构建-监护-契约-属性" (hash '#:collapsible-late-neg-projection #f '#:equivalent #f '#:exercise #f '#:first-order #f '#:generate #f '#:late-neg-projection #f '#:list-contract? #f '#:name #f '#:projection #f '#:stronger #f '#:val-first-projection #f))
  'build-contract-property  (cons "构建-契约-属性" (hash '#:collapsible-late-neg-projection #f '#:equivalent #f '#:exercise #f '#:first-order #f '#:generate #f '#:late-neg-projection #f '#:list-contract? #f '#:name #f '#:projection #f '#:stronger #f '#:trusted #f '#:val-first-projection #f))
  'build-flat-contract-property  (cons "构建-平坦-契约-属性" (hash '#:collapsible-late-neg-projection #f '#:equivalent #f '#:first-order #f '#:generate #f '#:late-neg-projection #f '#:list-contract? #f '#:name #f '#:projection #f '#:stronger #f '#:val-first-projection #f))
  'contract-exercise  (cons "契约-练习" (hash '#:fuel #f '#:shuffle? #f))
  'dynamic->*  (cons "动态->*" (hash '#:mandatory-domain-contracts #f '#:mandatory-keyword-contracts #f '#:mandatory-keywords #f '#:optional-domain-contracts #f '#:optional-keyword-contracts #f '#:optional-keywords #f '#:range-contracts #f '#:rest-contract #f))
  'flat-contract-with-explanation  (cons "平坦-契约-带-解释" (hash '#:name #f))
  'hash/c  (cons "哈希/契约" (hash '#:flat? #f '#:immutable #f))
  'make-chaperone-contract  (cons "创建-监护-契约" (hash '#:collapsible-late-neg-projection #f '#:equivalent #f '#:first-order #f '#:late-neg-projection #f '#:list-contract? #f '#:name #f '#:projection #f '#:stronger #f '#:val-first-projection #f))
  'make-contract  (cons "创建-契约" (hash '#:collapsible-late-neg-projection #f '#:equivalent #f '#:exercise #f '#:first-order #f '#:generate #f '#:late-neg-projection #f '#:list-contract? #f '#:name #f '#:projection #f '#:stronger #f '#:val-first-projection #f))
  'make-flat-contract  (cons "创建-平坦-契约" (hash '#:collapsible-late-neg-projection #f '#:equivalent #f '#:first-order #f '#:late-neg-projection #f '#:list-contract? #f '#:name #f '#:projection #f '#:stronger #f '#:val-first-projection #f))
  'parameter/c  (cons "参数/契约" (hash '#:impersonator? #f))
  'property/c  (cons "属性/契约" (hash '#:name #f))
  'raise-blame-error  (cons "引发-责备-错误" (hash '#:missing-party #f))
  'raise-not-cons-blame-error  (cons "引发-非-构造-责备-错误" (hash '#:missing-party #f))
  'treelist/c  (cons "树列表/契约" (hash '#:flat? #f '#:lazy? #f))
  'vector/c  (cons "向量/契约" (hash '#:flat? #f '#:immutable #f))
  'vectorof  (cons "向量之" (hash '#:eager #f '#:flat? #f '#:immutable #f))
))
