;; racket/match/patterns
#lang racket/base
(provide plain-map re-exports)

;; re-exports (0)
(define re-exports '())

;; plain (0/130 translated)
(define plain-map (hash
  '-struct:Row  #f
  'And  #f
  'And-ps  #f
  'And?  #f
  'App  #f
  'App-expr  #f
  'App-ps  #f
  'App?  #f
  'Box  #f
  'Box-p  #f
  'Box?  #f
  'CPat  #f
  'CPat?  #f
  'Dummy  #f
  'Dummy?  #f
  'Exact  #f
  'Exact-v  #f
  'Exact?  #f
  'GSeq  #f
  'GSeq-headss  #f
  'GSeq-maxs  #f
  'GSeq-mins  #f
  'GSeq-mutable?  #f
  'GSeq-onces?  #f
  'GSeq-tail  #f
  'GSeq?  #f
  'MPair  #f
  'MPair-a  #f
  'MPair-d  #f
  'MPair?  #f
  'Not  #f
  'Not-p  #f
  'Not?  #f
  'Null  #f
  'Null-p  #f
  'Null?  #f
  'Or  #f
  'Or-ps  #f
  'Or?  #f
  'OrderedAnd  #f
  'OrderedAnd?  #f
  'Pair  #f
  'Pair-a  #f
  'Pair-d  #f
  'Pair?  #f
  'Pat  #f
  'Pat?  #f
  'Pred  #f
  'Pred-pred  #f
  'Pred?  #f
  'Row  #f
  'Row-first-pat  #f
  'Row-pats  #f
  'Row-rhs  #f
  'Row-split-pats  #f
  'Row-unmatch  #f
  'Row-vars-seen  #f
  'Row?  #f
  'Struct  #f
  'Struct-accessors  #f
  'Struct-complete?  #f
  'Struct-id  #f
  'Struct-pred  #f
  'Struct-ps  #f
  'Struct-super  #f
  'Struct?  #f
  'Var  #f
  'Var-v  #f
  'Var?  #f
  'Vector  #f
  'Vector-ps  #f
  'Vector?  #f
  'acc-prop  #f
  'acc-prop-acc  #f
  'acc-prop-n  #f
  'acc-prop?  #f
  'bound-vars  #f
  'copy-mapping  #f
  'current-form-name  #f
  'current-renaming  #f
  'legacy-match-expander-proc  #f
  'legacy-match-expander?  #f
  'make-And  #f
  'make-App  #f
  'make-Box  #f
  'make-CPat  #f
  'make-Dummy  #f
  'make-Exact  #f
  'make-GSeq  #f
  'make-MPair  #f
  'make-Not  #f
  'make-Null  #f
  'make-Or  #f
  'make-OrderedAnd  #f
  'make-Pair  #f
  'make-Pat  #f
  'make-Pred  #f
  'make-Row  #f
  'make-Struct  #f
  'make-Var  #f
  'make-Vector  #f
  'make-struct-type-property/accessor  #f
  'match-...-nesting  #f
  'match-expander-proc  #f
  'match-expander?  #f
  'merge  #f
  'pat-key  #f
  'pats->bound-vars  #f
  'prop:legacy-match-expander  #f
  'prop:match-expander  #f
  'struct:And  #f
  'struct:App  #f
  'struct:Box  #f
  'struct:CPat  #f
  'struct:Dummy  #f
  'struct:Exact  #f
  'struct:GSeq  #f
  'struct:MPair  #f
  'struct:Not  #f
  'struct:Null  #f
  'struct:Or  #f
  'struct:OrderedAnd  #f
  'struct:Pair  #f
  'struct:Pat  #f
  'struct:Pred  #f
  'struct:Row  #f
  'struct:Struct  #f
  'struct:Var  #f
  'struct:Vector  #f
  'struct:acc-prop  #f
))

