;; ffi/unsafe
#lang racket/base
(provide plain-map kw-map re-exports)

;; re-exports (0)
(define re-exports '())

;; plain (155/157 translated)
(define plain-map (hash
  '->  #f
  '_?  #f
  '_array  "_数组"
  '_array/list  "_数组/列表"
  '_array/vector  "_数组/向量"
  '_bitmask  "_位掩码"
  '_bool  "_布尔"
  '_box  "_盒"
  '_byte  "_字节"
  '_bytes  "_字节串"
  '_bytes/eof  "_字节串/文件尾"
  '_bytes/nul-terminated  "_字节串/空-终止"
  '_cpointer  "_C指针"
  '_cpointer/null  "_C指针/空"
  '_double  "_双精度"
  '_double*  "_双精度*"
  '_file  "_文件"
  '_fixint  "_定长整数"
  '_fixnum  "_定长数"
  '_float  "_单精度"
  '_fpointer  "_函数指针"
  '_fun  "_函数"
  '_gcable  "_可GC"
  '_gcpointer  "_GC指针"
  '_int  "_整数"
  '_int16  "_整数16"
  '_int32  "_整数32"
  '_int64  "_整数64"
  '_int8  "_整数8"
  '_intmax  "_最大整数"
  '_intptr  "_整数指针"
  '_list  "_列表"
  '_llong  "_长长整数"
  '_long  "_长整数"
  '_longdouble  "_长双精度"
  '_or-null  "_或-空"
  '_path  "_路径"
  '_pointer  "_指针"
  '_ptr  "_指"
  '_ptrdiff  "_指针差"
  '_racket  "_Racket"
  '_sbyte  "_有符号字节"
  '_scheme  "_Scheme"
  '_short  "_短整数"
  '_sint  "_有符号整数"
  '_sint16  "_有符号整数16"
  '_sint32  "_有符号整数32"
  '_sint64  "_有符号整数64"
  '_sint8  "_有符号整数8"
  '_sintptr  "_有符号整数指针"
  '_size  "_大小"
  '_sllong  "_有符号长长整数"
  '_slong  "_有符号长整数"
  '_sshort  "_有符号短整数"
  '_ssize  "_有符号大小"
  '_stdbool  "_标准布尔"
  '_string  "_字符串"
  '_string*/latin-1  "_字符串*/拉丁-1"
  '_string*/locale  "_字符串*/区域"
  '_string*/utf-8  "_字符串*/UTF-8"
  '_string/eof  "_字符串/文件尾"
  '_string/latin-1  "_字符串/拉丁-1"
  '_string/locale  "_字符串/区域"
  '_string/ucs-4  "_字符串/UCS-4"
  '_string/utf-16  "_字符串/UTF-16"
  '_string/utf-8  "_字符串/UTF-8"
  '_sword  "_有符号字"
  '_symbol  "_符号"
  '_ubyte  "_无符号字节"
  '_ufixint  "_无符号定长整数"
  '_ufixnum  "_无符号定长数"
  '_uint  "_无符号整数"
  '_uint16  "_无符号整数16"
  '_uint32  "_无符号整数32"
  '_uint64  "_无符号整数64"
  '_uint8  "_无符号整数8"
  '_uintmax  "_无符号最大整数"
  '_uintptr  "_无符号整数指针"
  '_ullong  "_无符号长长整数"
  '_ulong  "_无符号长整数"
  '_union  "_联合"
  '_ushort  "_无符号短整数"
  '_uword  "_无符号字"
  '_vector  "_向量"
  '_void  "_空"
  '_wchar  "_宽字符"
  '_word  "_字"
  'array-length  "数组-长度"
  'array-ptr  "数组-指针"
  'array-ref  "数组-引用"
  'array-set!  "数组-设置!"
  'array-type  "数组-类型"
  'array?  "数组?"
  'cast  "类型转换"
  'cblock->list  "C块->列表"
  'cblock->vector  "C块->向量"
  'compiler-sizeof  "编译器-sizeof"
  'compute-offsets  "计算-偏移"
  'cpointer-gcable?  "C指针-GC可及?"
  'cpointer-has-tag?  "C指针-有-标签?"
  'cpointer-predicate-procedure?  "C指针-谓词-过程?"
  'cpointer-push-tag!  "C指针-推入-标签!"
  'cpointer-tag  "C指针-标签"
  'cpointer?  "C指针?"
  'ctype->layout  "C类型->布局"
  'ctype-alignof  "C类型-对齐"
  'ctype-sizeof  "C类型-sizeof"
  'ctype?  "C类型?"
  'default-_string-type  "默认-_字符串-类型"
  'define-c  "定义-C"
  'define-cpointer-type  "定义-C指针-类型"
  'define-cstruct  "定义-C结构"
  'define-fun-syntax  "定义-函数-语法"
  'end-stubborn-change  "结束-顽固-更改"
  'extflvector->cpointer  "扩展浮点向量->C指针"
  'ffi-lib-name  "FFI-库-名称"
  'ffi-lib?  "FFI-库?"
  'ffi-obj-ref  "FFI-对象-引用"
  'flvector->cpointer  "浮点向量->C指针"
  'free  "释放"
  'free-immobile-cell  "释放-不可移动-单元"
  'function-ptr  "函数-指针"
  'get-ffi-obj  "获取-FFI-对象"
  'in-array  "在-数组"
  'lookup-errno  "查找-errno"
  'make-array-type  "创建-数组-类型"
  'make-c-parameter  "创建-C-参数"
  'make-cstruct-type  "创建-C结构-类型"
  'make-ctype  "创建-C类型"
  'make-late-weak-box  "创建-后期-弱-盒"
  'make-late-weak-hasheq  "创建-后期-弱-哈希相等"
  'make-sized-byte-string  "创建-定长-字节-字符串"
  'make-union-type  "创建-联合-类型"
  'malloc  "malloc"
  'malloc-immobile-cell  "malloc-不可移动-单元"
  'memcpy  "memcpy"
  'memmove  "memmove"
  'memset  "memset"
  'offset-ptr?  "偏移-指针?"
  'prop:cpointer  "属性:C指针"
  'ptr-add  "指针-加"
  'ptr-add!  "指针-加!"
  'ptr-equal?  "指针-相等?"
  'ptr-offset  "指针-偏移"
  'ptr-ref  "指针-引用"
  'ptr-set!  "指针-设置!"
  'register-finalizer  "注册-终结器"
  'saved-errno  "已保存-errno"
  'set-cpointer-tag!  "设置-C指针-标签!"
  'set-ffi-obj!  "设置-FFI-对象!"
  'set-ptr-offset!  "设置-指针-偏移!"
  'union-ptr  "联合-指针"
  'union-ref  "联合-引用"
  'union-set!  "联合-设置!"
  'union?  "联合?"
  'vector->cpointer  "向量->C指针"
  'void/reference-sink  "空/引用-接收器"
))

;; with-kw (6)
(define kw-map (hash
  '_cprocedure  (cons "_C过程" (hash '#:abi "ABI" '#:async-apply "异步-应用" '#:atomic? "原子?" '#:blocking? "阻塞?" '#:callback-exns? "回调-异常?" '#:in-original-place? "在-原始-位置?" '#:keep "保持" '#:lock-name "锁-名称" '#:save-errno "保存-errno" '#:varargs-after "可变参数-之后" '#:wrapper "包装器"))
  '_enum  (cons "_枚举" (hash '#:unknown "未知"))
  '_list-struct  (cons "_列表-结构" (hash '#:alignment "对齐" '#:malloc-mode "malloc-模式"))
  'ffi-lib  (cons "FFI-库" (hash '#:custodian "管理员" '#:fail "失败" '#:get-lib-dirs "获取-库-目录" '#:global? "全局?"))
  'list->cblock  (cons "列表->C块" (hash '#:malloc-mode "malloc-模式"))
  'vector->cblock  (cons "向量->C块" (hash '#:malloc-mode "malloc-模式"))
))
