;; framework/main
#lang racket/base
(provide plain-map kw-map re-exports)

;; re-exports (4)
(define re-exports '(
  "framework/decorated-editor-snip"
  "framework/gui-utils"
  "framework/preferences"
  "framework/test"
))

;; plain (405)
(define plain-map (hash
  'application:current-app-name  #f
  'autosave:autosavable<%>  #f
  'autosave:current-toc-path  #f
  'autosave:register  #f
  'autosave:restore-autosave-files/gui  #f
  'autosave:toc-path  #f
  'canvas:basic%  #f
  'canvas:basic-mixin  #f
  'canvas:basic<%>  #f
  'canvas:color%  #f
  'canvas:color-mixin  #f
  'canvas:color<%>  #f
  'canvas:delegate%  #f
  'canvas:delegate-mixin  #f
  'canvas:delegate<%>  #f
  'canvas:info%  #f
  'canvas:info-mixin  #f
  'canvas:info<%>  #f
  'canvas:wide-snip%  #f
  'canvas:wide-snip-mixin  #f
  'canvas:wide-snip<%>  #f
  'color-model:hsl->rgb  #f
  'color-model:rgb->hsl  #f
  'color-model:rgb->xyz  #f
  'color-model:rgb-color-distance  #f
  'color-model:xyz->rgb  #f
  'color-model:xyz-x  #f
  'color-model:xyz-y  #f
  'color-model:xyz-z  #f
  'color-model:xyz?  #f
  'color-prefs:add-background-preferences-panel  #f
  'color-prefs:black-on-white  #f
  'color-prefs:color-scheme-color-name?  #f
  'color-prefs:color-scheme-style-name?  #f
  'color-prefs:get-color-scheme-names  #f
  'color-prefs:get-inverted-base-color-scheme  #f
  'color-prefs:known-color-scheme-name?  #f
  'color-prefs:marshall-style-delta  #f
  'color-prefs:normalize-color-selection-button-widths  #f
  'color-prefs:register-info-based-color-schemes  #f
  'color-prefs:set-current-color-scheme  #f
  'color-prefs:set-default/color-scheme  #f
  'color-prefs:set-in-color-scheme  #f
  'color-prefs:unmarshall-style-delta  #f
  'color-prefs:white-on-black  #f
  'color-prefs:white-on-black-color-scheme?  #f
  'color:get-parenthesis-colors-table  #f
  'color:misspelled-text-color-style-name  #f
  'color:text%  #f
  'color:text-mixin  #f
  'color:text-mode%  #f
  'color:text-mode-mixin  #f
  'color:text-mode<%>  #f
  'color:text<%>  #f
  'comment-box:snip%  #f
  'comment-box:snipclass  #f
  'editor-snip:decorated%  #f
  'editor-snip:decorated-mixin  #f
  'editor-snip:decorated-snipclass%  #f
  'editor-snip:decorated<%>  #f
  'editor:add-after-user-keymap  #f
  'editor:autoload-mixin  #f
  'editor:autoload<%>  #f
  'editor:autowrap-mixin  #f
  'editor:autowrap<%>  #f
  'editor:backup-autosave-mixin  #f
  'editor:backup-autosave<%>  #f
  'editor:basic-mixin  #f
  'editor:basic<%>  #f
  'editor:doing-autosave?  #f
  'editor:file-mixin  #f
  'editor:file<%>  #f
  'editor:font-size-message%  #f
  'editor:font-size-pref->current-font-size  #f
  'editor:get-change-font-size-when-monitors-change?  #f
  'editor:get-current-preferred-font-size  #f
  'editor:get-default-color-style-name  #f
  'editor:get-standard-style-list  #f
  'editor:info-mixin  #f
  'editor:info<%>  #f
  'editor:keymap-mixin  #f
  'editor:keymap<%>  #f
  'editor:set-change-font-size-when-monitors-change?  #f
  'editor:set-current-preferred-font-size  #f
  'editor:set-default-font-color  #f
  'editor:set-standard-style-list-delta  #f
  'editor:set-standard-style-list-pref-callbacks  #f
  'editor:silent-cancel-on-save-file-out-of-date?  #f
  'editor:standard-style-list-mixin  #f
  'editor:standard-style-list<%>  #f
  'exit:can-exit?  #f
  'exit:exit  #f
  'exit:exiting?  #f
  'exit:insert-can?-callback  #f
  'exit:insert-on-callback  #f
  'exit:on-exit  #f
  'exit:set-exiting  #f
  'exit:user-oks-exit  #f
  'finder:common-get-file  #f
  'finder:common-put-file  #f
  'finder:default-extension  #f
  'finder:default-filters  #f
  'finder:dialog-parent-parameter  #f
  'finder:get-file  #f
  'finder:put-file  #f
  'finder:std-get-file  #f
  'finder:std-put-file  #f
  'frame:add-snip-menu-items  #f
  'frame:basic%  #f
  'frame:basic-mixin  #f
  'frame:basic<%>  #f
  'frame:current-icon  #f
  'frame:delegate%  #f
  'frame:delegate-mixin  #f
  'frame:delegate<%>  #f
  'frame:editor%  #f
  'frame:editor-mixin  #f
  'frame:editor<%>  #f
  'frame:focus-table-mixin  #f
  'frame:focus-table<%>  #f
  'frame:info%  #f
  'frame:info-mixin  #f
  'frame:info<%>  #f
  'frame:lookup-focus-table  #f
  'frame:pasteboard%  #f
  'frame:pasteboard-info%  #f
  'frame:pasteboard-info-mixin  #f
  'frame:pasteboard-info<%>  #f
  'frame:pasteboard-mixin  #f
  'frame:pasteboard<%>  #f
  'frame:register-group-mixin  #f
  'frame:register-group<%>  #f
  'frame:remove-empty-menus  #f
  'frame:reorder-menus  #f
  'frame:searchable%  #f
  'frame:searchable-mixin  #f
  'frame:searchable-text-mixin  #f
  'frame:searchable-text<%>  #f
  'frame:searchable<%>  #f
  'frame:size-pref%  #f
  'frame:size-pref-mixin  #f
  'frame:size-pref<%>  #f
  'frame:standard-menus%  #f
  'frame:standard-menus-mixin  #f
  'frame:standard-menus<%>  #f
  'frame:status-line%  #f
  'frame:status-line-mixin  #f
  'frame:status-line<%>  #f
  'frame:text%  #f
  'frame:text-info%  #f
  'frame:text-info-mixin  #f
  'frame:text-info<%>  #f
  'frame:text-mixin  #f
  'frame:text<%>  #f
  'group:%  #f
  'group:add-to-windows-menu  #f
  'group:can-close-check  #f
  'group:create-windows-menu  #f
  'group:get-the-frame-group  #f
  'group:on-close-action  #f
  'handler:add-to-recent  #f
  'handler:current-create-new-window  #f
  'handler:find-format-handler  #f
  'handler:find-named-format-handler  #f
  'handler:handler-extension  #f
  'handler:handler-handler  #f
  'handler:handler-name  #f
  'handler:handler?  #f
  'handler:insert-format-handler  #f
  'handler:install-recent-items  #f
  'handler:open-file  #f
  'handler:set-recent-items-frame-superclass  #f
  'handler:set-recent-position  #f
  'handler:size-recently-opened-files  #f
  'handler:update-currently-open-files  #f
  'icon:get-anchor-bitmap  #f
  'icon:get-autowrap-bitmap  #f
  'icon:get-eof-bitmap  #f
  'icon:get-gc-off-bitmap  #f
  'icon:get-gc-on-bitmap  #f
  'icon:get-left/right-cursor  #f
  'icon:get-lock-bitmap  #f
  'icon:get-paren-highlight-bitmap  #f
  'icon:get-unlock-bitmap  #f
  'icon:get-up/down-cursor  #f
  'keymap:add-to-right-button-menu  #f
  'keymap:add-to-right-button-menu/before  #f
  'keymap:add-user-keybindings-file  #f
  'keymap:aug-keymap%  #f
  'keymap:aug-keymap-mixin  #f
  'keymap:aug-keymap<%>  #f
  'keymap:call/text-keymap-initializer  #f
  'keymap:canonicalize-keybinding-string  #f
  'keymap:get-editor  #f
  'keymap:get-file  #f
  'keymap:get-global  #f
  'keymap:get-search  #f
  'keymap:get-user  #f
  'keymap:make-meta-prefix-list  #f
  'keymap:region-click  #f
  'keymap:remove-chained-keymap  #f
  'keymap:remove-user-keybindings-file  #f
  'keymap:set-chained-keymaps  #f
  'keymap:setup-editor  #f
  'menu:can-restore-checkable-menu-item%  #f
  'menu:can-restore-menu-item%  #f
  'menu:can-restore-mixin  #f
  'menu:can-restore-underscore-menu%  #f
  'menu:can-restore-underscore-mixin  #f
  'menu:can-restore-underscore<%>  #f
  'menu:can-restore<%>  #f
  'mode:host-text-mixin  #f
  'mode:host-text<%>  #f
  'mode:surrogate-text%  #f
  'mode:surrogate-text<%>  #f
  'number-snip:get-number  #f
  'number-snip:is-number-snip?  #f
  'number-snip:make-fraction-snip  #f
  'number-snip:make-repeating-decimal-snip  #f
  'number-snip:remove-decimal-looking-number-snips-on-insertion-mixin  #f
  'number-snip:snip-class%  #f
  'panel:discrete-child<%>  #f
  'panel:discrete-sizes-mixin  #f
  'panel:discrete-sizes<%>  #f
  'panel:dragable-container-size  #f
  'panel:dragable-mixin  #f
  'panel:dragable-place-children  #f
  'panel:dragable<%>  #f
  'panel:horizontal-discrete-sizes%  #f
  'panel:horizontal-dragable%  #f
  'panel:horizontal-dragable-mixin  #f
  'panel:horizontal-dragable<%>  #f
  'panel:single%  #f
  'panel:single-mixin  #f
  'panel:single-pane%  #f
  'panel:single-window-mixin  #f
  'panel:single-window<%>  #f
  'panel:single<%>  #f
  'panel:splitter-mixin  #f
  'panel:splitter<%>  #f
  'panel:vertical-discrete-sizes%  #f
  'panel:vertical-dragable%  #f
  'panel:vertical-dragable-mixin  #f
  'panel:vertical-dragable<%>  #f
  'pasteboard:backup-autosave%  #f
  'pasteboard:basic%  #f
  'pasteboard:file%  #f
  'pasteboard:info%  #f
  'pasteboard:keymap%  #f
  'pasteboard:standard-style-list%  #f
  'path-utils:generate-autosave-name  #f
  'path-utils:generate-backup-name  #f
  'preferences:add-boolean-option-with-ask-me  #f
  'preferences:add-can-close-dialog-callback  #f
  'preferences:add-check  #f
  'preferences:add-editor-checkbox-panel  #f
  'preferences:add-font-panel  #f
  'preferences:add-general-checkbox-panel  #f
  'preferences:add-on-close-dialog-callback  #f
  'preferences:add-panel  #f
  'preferences:add-scheme-checkbox-panel  #f
  'preferences:add-to-editor-checkbox-panel  #f
  'preferences:add-to-general-checkbox-panel  #f
  'preferences:add-to-scheme-checkbox-panel  #f
  'preferences:add-to-warnings-checkbox-panel  #f
  'preferences:add-warnings-checkbox-panel  #f
  'preferences:get-preference/gui  #f
  'preferences:hide-dialog  #f
  'preferences:put-preferences/gui  #f
  'preferences:show-dialog  #f
  'preferences:show-tab-panel  #f
  'racket:add-coloring-preferences-panel  #f
  'racket:add-pairs-keybinding-functions  #f
  'racket:add-preferences-panel  #f
  'racket:default-paren-matches  #f
  'racket:get-color-prefs-table  #f
  'racket:get-keymap  #f
  'racket:get-non-paren-keymap  #f
  'racket:get-paren-keymap  #f
  'racket:get-white-on-black-color-prefs-table  #f
  'racket:get-wordbreak-map  #f
  'racket:init-wordbreak-map  #f
  'racket:set-mode-mixin  #f
  'racket:sexp-snip%  #f
  'racket:sexp-snip<%>  #f
  'racket:short-sym->pref-name  #f
  'racket:short-sym->style-name  #f
  'racket:text%  #f
  'racket:text-balanced?  #f
  'racket:text-mixin  #f
  'racket:text-mode%  #f
  'racket:text-mode-mixin  #f
  'racket:text-mode<%>  #f
  'racket:text<%>  #f
  'scheme:add-coloring-preferences-panel  #f
  'scheme:add-preferences-panel  #f
  'scheme:get-color-prefs-table  #f
  'scheme:get-keymap  #f
  'scheme:get-white-on-black-color-prefs-table  #f
  'scheme:get-wordbreak-map  #f
  'scheme:init-wordbreak-map  #f
  'scheme:set-mode-mixin  #f
  'scheme:sexp-snip%  #f
  'scheme:sexp-snip<%>  #f
  'scheme:short-sym->pref-name  #f
  'scheme:short-sym->style-name  #f
  'scheme:text%  #f
  'scheme:text-balanced?  #f
  'scheme:text-mixin  #f
  'scheme:text-mode%  #f
  'scheme:text-mode-mixin  #f
  'scheme:text-mode<%>  #f
  'scheme:text<%>  #f
  'srcloc-snip:select-srcloc  #f
  'srcloc-snip:snip%  #f
  'srcloc-snip:snipclass  #f
  'text:1-pixel-string-snip%  #f
  'text:1-pixel-tab-snip%  #f
  'text:all-string-snips-mixin  #f
  'text:all-string-snips<%>  #f
  'text:ascii-art-enlarge-boxes-mixin  #f
  'text:ascii-art-enlarge-boxes<%>  #f
  'text:autocomplete-append-after  #f
  'text:autocomplete-limit  #f
  'text:autocomplete-mixin  #f
  'text:autocomplete<%>  #f
  'text:autowrap%  #f
  'text:backup-autosave%  #f
  'text:basic%  #f
  'text:basic-mixin  #f
  'text:basic<%>  #f
  'text:clever-file-format%  #f
  'text:clever-file-format-mixin  #f
  'text:clever-file-format<%>  #f
  'text:column-guide-mixin  #f
  'text:column-guide<%>  #f
  'text:crlf-line-endings-mixin  #f
  'text:crlf-line-endings<%>  #f
  'text:delegate%  #f
  'text:delegate-mixin  #f
  'text:delegate<%>  #f
  'text:file%  #f
  'text:file-mixin  #f
  'text:file<%>  #f
  'text:first-line-mixin  #f
  'text:first-line<%>  #f
  'text:foreground-color-mixin  #f
  'text:foreground-color<%>  #f
  'text:get-completions/manuals  #f
  'text:hide-caret/selection%  #f
  'text:hide-caret/selection-mixin  #f
  'text:hide-caret/selection<%>  #f
  'text:indent-guides-mixin  #f
  'text:indent-guides<%>  #f
  'text:info%  #f
  'text:info-mixin  #f
  'text:info<%>  #f
  'text:inline-overview-mixin  #f
  'text:inline-overview-mpw-mixin  #f
  'text:inline-overview<%>  #f
  'text:input-box%  #f
  'text:input-box-mixin  #f
  'text:input-box<%>  #f
  'text:keymap%  #f
  'text:line-numbers-mixin  #f
  'text:line-numbers<%>  #f
  'text:line-spacing%  #f
  'text:line-spacing-mixin  #f
  'text:line-spacing<%>  #f
  'text:lookup-port-name  #f
  'text:make-snip-special  #f
  'text:max-width-paragraph-mixin  #f
  'text:max-width-paragraph<%>  #f
  'text:nbsp->space%  #f
  'text:nbsp->space-mixin  #f
  'text:nbsp->space<%>  #f
  'text:normalize-paste%  #f
  'text:normalize-paste-mixin  #f
  'text:normalize-paste<%>  #f
  'text:overwrite-disable-mixin  #f
  'text:overwrite-disable<%>  #f
  'text:ports-mixin  #f
  'text:ports<%>  #f
  'text:range-caret-space?  #f
  'text:range-color  #f
  'text:range-end  #f
  'text:range-start  #f
  'text:range-style  #f
  'text:range?  #f
  'text:return%  #f
  'text:return-mixin  #f
  'text:return<%>  #f
  'text:searching%  #f
  'text:searching-embedded-mixin  #f
  'text:searching-embedded<%>  #f
  'text:searching-mixin  #f
  'text:searching<%>  #f
  'text:send-snip-to-port  #f
  'text:snip-special?  #f
  'text:standard-style-list%  #f
  'text:wide-snip%  #f
  'text:wide-snip-mixin  #f
  'text:wide-snip<%>  #f
  'version:add-spec  #f
  'version:version  #f
))

;; with-kw (19)
(define kw-map (hash
  'color-prefs:add-color-scheme-entry  (cons #f (hash '#:background #f '#:bold? #f '#:italic? #f '#:style #f '#:underline? #f))
  'color-prefs:add-color-scheme-preferences-panel  (cons #f (hash '#:extras #f))
  'color-prefs:add-to-preferences-panel  (cons #f (hash '#:style #f))
  'color-prefs:build-color-selection-panel  (cons #f (hash '#:background? #f))
  'color-prefs:get-current-color-scheme-name  (cons #f (hash '#:wob? #f))
  'color-prefs:lookup-in-color-scheme  (cons #f (hash '#:wob? #f))
  'color-prefs:register-color-preference  (cons #f (hash '#:background #f))
  'color-prefs:register-color-scheme-entry-change-callback  (cons #f (hash '#:style-list #f))
  'frame:setup-size-pref  (cons #f (hash '#:maximized? #f '#:position-preferences #f))
  'handler:edit-file  (cons #f (hash '#:end-pos #f '#:start-pos #f))
  'keymap:send-map-function-meta  (cons #f (hash '#:alt-as-meta-keymap #f))
  'keymap:setup-file  (cons #f (hash '#:alt-as-meta-keymap #f))
  'keymap:setup-global  (cons #f (hash '#:alt-as-meta-keymap #f))
  'keymap:setup-search  (cons #f (hash '#:alt-as-meta-keymap #f))
  'number-snip:make-pretty-print-size  (cons #f (hash '#:exact-prefix #f '#:fraction-view #f '#:inexact-prefix #f))
  'number-snip:number->string/snip  (cons #f (hash '#:exact-prefix #f '#:fraction-view #f '#:inexact-prefix #f))
  'racket:map-pairs-keybinding-functions  (cons #f (hash '#:alt-as-meta-keymap #f))
  'racket:setup-keymap  (cons #f (hash '#:alt-as-meta-keymap #f '#:paren-alt-as-meta-keymap #f '#:paren-keymap #f))
  'scheme:setup-keymap  (cons #f (hash '#:alt-as-meta-keymap #f '#:paren-alt-as-meta-keymap #f '#:paren-keymap #f))
))
